spring.application.name=cheffy-order-service
spring.data.mongodb.uri=${MONGODB_URL:mongodb://admin:admin@localhost:27017/cheffy-order-service?authSource=admin}
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=admin
server.port=8083

payment.api.url=${PAYMENT_URL:http://localhost:8089}

#oauth2
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_URI:http://localhost:8085/.well-known/jwks.json}

############################################
# KAFKA
############################################

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS_URL:localhost:9092}
#spring.kafka.bootstrap-servers=kafka:29092

spring.kafka.consumer.group-id=order-service-group
spring.kafka.listener.ack-mode=record

# =========================
# RETRY
# =========================
logging.level.io.github.resilience4j.retry=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG

resilience4j.retry.instances.payment.max-attempts=6
resilience4j.retry.instances.payment.wait-duration=3s
resilience4j.retry.instances.payment.enable-exponential-backoff=true

# =========================
# CIRCUIT BREAKER
# =========================
resilience4j.circuitbreaker.instances.payment.sliding-window-size=10
resilience4j.circuitbreaker.instances.payment.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.payment.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.payment.wait-duration-in-open-state=30s

# =========================
# OPENFEIGN
# =========================
spring.cloud.openfeign.client.config.payment-service.connectTimeout=10000
spring.cloud.openfeign.client.config.payment-service.readTimeout=10000