spring.application.name=cheffy-order-service
spring.mongodb.uri=mongodb://localhost:27017/cheffy-order-service
server.port=8083

payment.api.url=http://localhost:8089

#oauth2
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/.well-known/jwks.json


